/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as RateLimitsRouteImport } from './routes/rate-limits'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as CircuitsRouteImport } from './routes/circuits'
import { Route as IndexRouteImport } from './routes/index'

const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const RateLimitsRoute = RateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsRoute = CircuitsRouteImport.update({
  id: '/circuits',
  path: '/circuits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circuits': typeof CircuitsRoute
  '/keys': typeof KeysRoute
  '/logs': typeof LogsRoute
  '/rate-limits': typeof RateLimitsRoute
  '/routes': typeof RoutesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circuits': typeof CircuitsRoute
  '/keys': typeof KeysRoute
  '/logs': typeof LogsRoute
  '/rate-limits': typeof RateLimitsRoute
  '/routes': typeof RoutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circuits': typeof CircuitsRoute
  '/keys': typeof KeysRoute
  '/logs': typeof LogsRoute
  '/rate-limits': typeof RateLimitsRoute
  '/routes': typeof RoutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/circuits' | '/keys' | '/logs' | '/rate-limits' | '/routes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/circuits' | '/keys' | '/logs' | '/rate-limits' | '/routes'
  id:
    | '__root__'
    | '/'
    | '/circuits'
    | '/keys'
    | '/logs'
    | '/rate-limits'
    | '/routes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircuitsRoute: typeof CircuitsRoute
  KeysRoute: typeof KeysRoute
  LogsRoute: typeof LogsRoute
  RateLimitsRoute: typeof RateLimitsRoute
  RoutesRoute: typeof RoutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-limits': {
      id: '/rate-limits'
      path: '/rate-limits'
      fullPath: '/rate-limits'
      preLoaderRoute: typeof RateLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits': {
      id: '/circuits'
      path: '/circuits'
      fullPath: '/circuits'
      preLoaderRoute: typeof CircuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircuitsRoute: CircuitsRoute,
  KeysRoute: KeysRoute,
  LogsRoute: LogsRoute,
  RateLimitsRoute: RateLimitsRoute,
  RoutesRoute: RoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
